version: "3"
services:

  casper-db:
    image: "postgres"
    environment:
      POSTGRES_USER: "casper-back"
      POSTGRES_PASSWORD: "casperdemo33221"
    restart: unless-stopped
    container_name: casper-db
    ports:
      - "5433:5432"

  casper-front:
    volumes:
      - "./casper-front/.env.local:/opt/app/casper-front/.env.local"
#      - "./front:/opt/app/casper-front"
    build:
      context: "./casper-front"
      dockerfile: Dockerfile
    restart: always
    container_name: casper-front
    command: ["npm", "run", "dev"]
    ports:
      - "4000:4000"

  casper-back:
    volumes:
      - "./casper-back/.env.local:/opt/app/casper-back/.env"
#      - "./back:/opt/app/casper-back"
#    tty: true
    build:
      context: "./casper-back"
      dockerfile: Dockerfile
    container_name: casper-back
    restart: always
    command: [ "npm","run", "start:dev" ]
    ports:
      - "3001:3001"

  casper-processor:
    container_name: casper-processor
    volumes:
      - "./processor/.env.local:/opt/app/casper-processor/.env"
    build:
      context: "./processor"
      dockerfile: Dockerfile
    restart: always
    command: ["npm", "run", "start"]
    ports:
      - "8085:3000"

  casper-rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: casper-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  back:

