version: "3"
services:
  casper-back:
    build:
      context: "./casper-back"
      dockerfile: Dockerfile
    restart: always
    container_name: casper-back
    command: ["npm","run", "start"]
    volumes:
    - "./casper-back/.env:/opt/app/casper-back/.env"
    environment:
      DB_HOST: "casper-db"
      DB_USER: "casper-back"
      DB_PASSWORD: "casperdemo33221"
      DB_DATABASE: "casper-back"
      SECRET_HASH: "qweqweqwe12312321qweqwe123123"
    ports:
      - "3001:3001"
  casper-db:
    image: "postgres"
    container_name: casper-db
    environment:
      POSTGRES_USER: "casper-back"
      POSTGRES_PASSWORD: "casperdemo33221"
    restart: always
    ports:
      - "5432:5432"

  casper-front:
    container_name: casper-front
    build:
      context: "./casper-front"
      dockerfile: Dockerfile
    restart: always
    command: ["npm", "run", "start"]
    ports:
     - "3000:3000"

  casper-processor:
    container_name: casper-processor
    build:
      context: "./processor"
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "./processor/.env:/opt/app/casper-processor/.env"
    environment:
      DB_HOST: "casper-db"
      DB_USER: "casper-back"
      DB_PASSWORD: "casperdemo33221"
      DB_DATABASE: "casper-back"
      SECRET_HASH: "qweqweqwe12312321qweqwe123123"
    command: ["npm", "run", "start"]

  casper-rabbitmq:
    container_name: casper-rabbitmq
    image: 'rabbitmq:3.6-management-alpine'

  varavel:
    container_name: casper-laravel
    build:
      context: "./laravel"
      dockerfile: Dockerfile
#      args:
#        user: sammy
#        uid: 1000
    restart: always
    volumes:
      - "./laravel:/app"
    ports:
    - "8181:8181"

